title: Gitでよく使うコマンド
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs

repositry: HappyApple1/template

permalink: pretty

defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
